# Generated by Django 2.1.7 on 2019-04-29 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0002_remove_movie_movie_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_time',
            field=models.CharField(max_length=50),
        ),
    ]
